services:
  db:
    image: pgvector/pgvector:pg15
    environment:
      POSTGRES_USER: newslens_user
      POSTGRES_PASSWORD: newslens_password
      POSTGRES_DB: newslens
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./Backend/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./Backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://newslens_user:newslens_password@db:5432/newslens
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=your_secret_key_here
      - NEWSAPI_KEY=${NEWSAPI_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - FRONTEND_URL=http://localhost:3000
      - HF_TOKEN=${HF_TOKEN}
      - HF_MODEL=${HF_MODEL}
    depends_on:
      - db
      - redis

  worker:
    build:
      context: ./Backend
    command: rq worker default -u redis://redis:6379/0
    environment:
      - DATABASE_URL=postgresql://newslens_user:newslens_password@db:5432/newslens
      - REDIS_URL=redis://redis:6379/0
      - NEWSAPI_KEY=${NEWSAPI_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - HF_TOKEN=${HF_TOKEN}
      - HF_MODEL=${HF_MODEL}
    depends_on:
      - redis
      - db

  frontend:
    build:
      context: ./Frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    depends_on:
      - backend

volumes:
  pgdata:
