services:
  - type: web
    name: newslens-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: NEWSAPI_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false

  - type: worker
    name: newslens-worker
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: rq worker default -u $REDIS_URL
    envVars:
      - key: NEWSAPI_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false