"""Add country language news_scope to User

Revision ID: 98ee755e6964
Revises: af4edea29ab8
Create Date: 2026-05-31 17:26:28.186174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98ee755e6964'
down_revision = 'af4edea29ab8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=5), server_default='us', nullable=False))
        batch_op.add_column(sa.Column('language', sa.String(length=10), server_default='en', nullable=False))
        batch_op.add_column(sa.Column('news_scope', sa.String(length=50), server_default='GLOBAL', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('news_scope')
        batch_op.drop_column('language')
        batch_op.drop_column('country')

    # ### end Alembic commands ###
