"""add url_to_image

Revision ID: af4edea29ab8
Revises: cd47f9fa8974
Create Date: 2026-05-29 01:18:31.873817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af4edea29ab8'
down_revision = 'cd47f9fa8974'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_to_image', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('url_to_image')

    # ### end Alembic commands ###
