"""add_saved_articles_v2

Revision ID: db7614f5633a
Revises: 98ee755e6964
Create Date: 2026-05-31 19:30:45.580746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db7614f5633a'
down_revision = '98ee755e6964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('saved_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'article_id', name='uq_user_article')
    )
    with op.batch_alter_table('saved_articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_articles_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_articles_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_articles_user_id'))
        batch_op.drop_index(batch_op.f('ix_saved_articles_article_id'))

    op.drop_table('saved_articles')
    # ### end Alembic commands ###
